// Code generated by dagger. DO NOT EDIT.

package dagger

import (
	"context"
	"encoding/json"

	"github.com/dagger/querybuilder"
)

func (r *Query) TestEnv() *TestEnv { // test-env (../../../../../:0:0)
	q := r.query.Select("testEnv")

	return &TestEnv{
		query: q,
	}
}

type TestEnv struct { // test-env (../../../../../:0:0)
	query *querybuilder.Selection

	id *ID
}

func (r *TestEnv) WithGraphQLQuery(q *querybuilder.Selection) *TestEnv {
	return &TestEnv{
		query: q,
	}
}

// Base returns the complete container used by the Go module for tests.
func (r *TestEnv) Base() *Container {
	q := r.query.Select("base")

	return &Container{
		query: q,
	}
}

// A unique identifier for this TestEnv.
func (r *TestEnv) ID(ctx context.Context) (ID, error) {
	if r.id != nil {
		return *r.id, nil
	}
	q := r.query.Select("id")

	var response ID

	q = q.Bind(&response)
	return response, q.Execute(ctx)
}

// XXX_GraphQLType is an internal function. It returns the native GraphQL type name
func (r *TestEnv) XXX_GraphQLType() string {
	return "TestEnv"
}

// XXX_GraphQLIDType is an internal function. It returns the native GraphQL type name for the ID of this object
func (r *TestEnv) XXX_GraphQLIDType() string {
	return "ID"
}

// XXX_GraphQLID is an internal function. It returns the underlying type ID
func (r *TestEnv) XXX_GraphQLID(ctx context.Context) (string, error) {
	id, err := r.ID(ctx)
	if err != nil {
		return "", err
	}
	return string(id), nil
}

func (r *TestEnv) MarshalJSON() ([]byte, error) {
	id, err := r.ID(marshalCtx)
	if err != nil {
		return nil, err
	}
	return json.Marshal(id)
}
func (r *TestEnv) UnmarshalJSON(bs []byte) error {
	var id string
	err := json.Unmarshal(bs, &id)
	if err != nil {
		return err
	}
	*r = TestEnv{query: selectNode(dag.query, id, "TestEnv")}
	return nil
}
