name: Check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  dagger:
    name: Dagger check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Generate Dagger files
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "0.21.8"
          dagger-flags: --x-release v1.0.0-beta.9 --progress plain --auto-apply
          verb: generate
      - name: Show generated changes
        run: git diff --exit-code
      - name: Run Dagger checks
        uses: dagger/dagger-for-github@v8.4.1
        with:
          version: "0.21.8"
          dagger-flags: --x-release v1.0.0-beta.9 --progress plain
          verb: check
